manifest:
  id: danil0vsky.bestbyyear
  version: 1.0.0
  name: Danil0vsky Best By Year
  description: A simple and much needed movies/series filter by year and rating
  types:
    - movie
    - series
  catalogs:
    - type: movie
      id: Best By Year
      extra:
        - name: genre
          options:
            - "2000"
            - "2001"
            - "2002"
            - "2003"
            - "2004"
            - "2005"
            - "2006"
            - "2007"
            - "2008"
            - "2009"
            - "2010"
            - "2011"
            - "2012"
            - "2013"
            - "2014"
            - "2015"
            - "2016"
            - "2017"
            - "2018"
            - "2019"
            - "2020"
            - "2021"
            - "2022"
            - "2023"
            - "2024"
            # Add more years up to the current year
          isRequired: true
    - type: series
      id: Hello, Ruby
      extra:
        - name: genre
          options:
            - "2000"
            - "2001"
            - "2002"
            - "2003"
            - "2004"
            - "2005"
            - "2006"
            - "2007"
            - "2008"
            - "2009"
            - "2010"
            - "2011"
            - "2012"
            - "2013"
            - "2014"
            - "2015"
            - "2016"
            - "2017"
            - "2018"
            - "2019"
            - "2020"
            - "2021"
            - "2022"
            - "2023"
            - "2024"
            # Add more years up to the current year
          isRequired: true
  resources:
    - catalog
