version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
    working_dir: /myapp
    command: ["rails", "server", "-b", "0.0.0.0", "-p", "8080"]
    ports:
      - "8080:8080"
    environment:
      RAILS_ENV: development
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
